version: '3'

services:
  fullfaq-home:
    # Собранный GitHub Actions образ, опубликованный в GHCR
    image: ghcr.io/ephemeral172/fullfaq-site:latest
    # Если вы делаете stack в Portainer, обычно удобнее задавать IMAGE_OWNER в Environment variables
    # IMAGE_OWNER=<github-owner>

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fullfaq.rule=Host(`fullfaq.dev`)"
      - "traefik.http.routers.fullfaq.entrypoints=websecure"
      - "traefik.http.routers.fullfaq.tls=true"
      - "traefik.http.services.fullfaq.loadbalancer.server.port=80"
      - "traefik.http.routers.fullfaq.tls.certresolver=leresolver"

    networks:
      - traefik_net

    restart: unless-stopped

networks:
  traefik_net:
    external: true