server {
    listen 80;
    server_name axioma8.ru www.axioma8.ru;
    root /usr/share/nginx/html;
    
    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache, no-store";
    }
    
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }
    
    # Временное правило для неправильных путей - ВНУТРИ server блока
    location ~ ^/src/public/(.+)$ {
        try_files /$1 =404;
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }
    
    error_page 404 /index.html;
}